paths:
  data_raw: "kaitiaki/data/raw"
  data_processed: "kaitiaki/data/processed"
  bm25_index: "kaitiaki/data/processed/bm25_index.pkl"
  bm25_meta:  "kaitiaki/data/processed/bm25_meta.json"

qdrant:
  host: "127.0.0.1"
  port: 6333
  collection: "kaitiaki_v1"

models:
  embedding: "sentence-transformers/all-MiniLM-L6-v2"
  reranker: "BAAI/bge-reranker-base"
  llm_base_url: "http://127.0.0.1:8000/v1"   # OpenAI-like endpoint (vLLM/serveur maison)
  llm_model: "local/llama-3.1-8b-instruct"
  llm_max_ctx: 4096

retrieval:
  top_k_dense: 20
  top_k_bm25: 20
  fusion: "rrf"
  rerank_top_k: 25

ui:
  default_days: 180
